### ISSUE TITLE
N26 import failes with Bad Request (YNAB::ApiError)

### ISSUE THREAD

**Issue by moritzrupp** [schurig/ynab-bank-importer#14] opened 2018-08-22 19:42 UTC
Hey @schurig,

I recently found your great work and I wanted to try it out.
Unfortunately, it is failing for my N26 account.

I have set up all the required fields in `config.yml` for the N26 dumper like this:

```yml
accounts:
  - dumper: :n26
    iban: 'myn26iban' # n26 iban
    ynab_id: 'my_ynab_id' # last hash in the url when you click on the account in YNAB
    username: 'my@mail.com' # n26 username
    password: 'my$pecialP4ssw0rd' # n26 password
    set_category: false # default: false, sets the N26 category name as category
```

When I execute the docker image I'm getting the following error:

```sh
$ docker-compose run importer
Traceback (most recent call last):
	3: from /usr/app/run.rb:21:in `<main>'
	2: from /usr/local/bundle/gems/ynab-1.2.0/lib/ynab/api/transactions_api.rb:29:in `bulk_create_transactions'
	1: from /usr/local/bundle/gems/ynab-1.2.0/lib/ynab/api/transactions_api.rb:68:in `bulk_create_transactions_with_http_info'
/usr/local/bundle/gems/ynab-1.2.0/lib/ynab/api_client.rb:68:in `call_api': Bad Request (YNAB::ApiError)
$
```

I'm completely new to Ruby, so cannot say a lot about the code. I have tested the API with my credentials using Postman and it is working. Apparently, the code is failing during the creation of the transactions.

Is N26 currently working for you?

It is working fine with my DKB account.

Thanks a lot!
Moritz

**Comment by schurig** [comment] 2018-08-23 05:48
Hi @moritzrupp, thanks for reporting the error.

It looks like an error coming from the YNAB API during the import process. So I guess that the transactions from N26 are already fetched but for some reason it can't make the request to create it.

I'll have a look today or one of the next days and try to reproduce it with my N26 account :)

**Comment by schurig** [comment] 2018-08-23 16:14
@moritzrupp I just tried to reproduce it and I got the same error when I put a wrong `ynab_id` in. Can you double check that this id is correct?

You can find it here:

`https://app.youneedabudget.com/`**`BUDGET_ID`**`/accounts/`**`THIS_ONE_YOU_NEED`**

**Comment by moritzrupp** [comment] 2018-08-24 07:17
Hey @schurig,

I tried it again today. I made sure that the `ynab_id` matches 100%. I'm still getting the error.
Is there any way to print/log/debug the the request in a readable format?

Furthermore, when I use a different dumper (e.g. `:fints`) it is working this the account ID which is failing for N26.

**Comment by schurig** [comment] 2018-08-24 08:00
Sadly the official ynab library that I'm using seems to not log anything. I'll have a look because I think there was an ongoing PR regarding that. Would be much better to see the error message. Still strange why it doesn't work for you but for me then, I'm importing N26 transactions every day.

I'll let you know when I have a better idea how we can log it :)

**Comment by schurig** [comment] 2018-08-25 09:09
@moritzrupp I just pushed a new version _(#17, I just merged it into `master`)_ that prints out more information about the error. Can you please try it out and see what it says?

You might have to run a `docker-compose pull` before so that docker pulls the latest release from the registry. 🤞

**Comment by moritzrupp** [comment] 2018-08-29 09:45
Hey @schurig,

your update is great. I'm getting the following error description:

```
$ docker-compose run importer
⚠️  YNAB API Error: bad_request (400)

Returned error message:
{
  "transactions": [
    {
      "index": 63,
      "error": {
        "memo": [
          "is too long (maximum is 100 characters)"
        ]
      }
    }
  ]
}

What you can do about the error:

→ Please consider reading the error message above to find out more.
```

Which is now pretty obvious. The memo field is too long.
Currently it is composed of the reference text and the merchant city. Should it just be truncated to 100 characters? If yes, I could submit a PR.

**Comment by schurig** [comment] 2018-08-29 10:08
@moritzrupp awesome, glad to hear it worked! Thanks for posing the error.

If you want you can submit it as a PR. I would suggest to add the logic in `lib/transaction_creator.rb` because it might effect other banks as well. Here is a suggestion that should do the job:

```ruby
def memo(options)
  memo = options.fetch(:memo, nil)
  # The api has a limit of 100 characters for the momo field
  memo = truncate(memo, 100)
  return "ATM withdrawal #{memo}" if withdrawal?(options)
  memo
end

# ...

# Helper methods

def truncate(string, max)
  string.length > max ? string[0...max] : string
end
```

Let me know if you need help. It would be cool if you could name the branch something like `feature/limit-memo-size` when you create the PR, but if not, no worries.

**Closed** 2018-09-06 08:09 UTC
Labels: N26, investigating
